@baseUrl = https://localhost:5443
@accessToken = eyJhbGciOiJFUzI1NiIsImtpZCI6ImQ0MjUwY2MxLTZhNTEtNDNlYS05MWRjLWJkMmU0ZjcyMDU0NCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3pvaGVueHRicW1ucWdibG15cXZyLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJkZjMzOThmYy1jOTRiLTRlMmYtOGM4YS0xMDUzNTkwZDBiN2EiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg4OTE3NjAwLCJpYXQiOjE3ODg5MTQwMDAsImVtYWlsIjoiYmlha2NldTkxMkBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiYmlha2NldTkxMkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZnVsbF9uYW1lIjoiQmlhayIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiZGYzMzk4ZmMtYzk0Yi00ZTJmLThjOGEtMTA1MzU5MGQwYjdhIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3ODg5MTQwMDB9XSwic2Vzc2lvbl9pZCI6ImZiMTI5MTZlLWMzNWYtNGU2NS04ZjdjLWQ0YTEzYTY0NTRlOSIsImlzX2Fub255bW91cyI6ZmFsc2V9.VnLVJfMHMXOQO0OXR9KPRXcvKO4r65ov5_sXMTbAAMKVymVxjscG9xS373vtgJNfI_uch3Y2zhvasptHSf3MOw

### Auth Test
GET {{baseUrl}}/user
Authorization: Bearer {{accessToken}}

### Get Current User
GET {{baseUrl}}/profiles/me
Authorization: Bearer {{accessToken}}
